"""empty message

Revision ID: c9a51aa0ce64
Revises: 11aca2b0af98
Create Date: 2025-07-23 20:49:09.729780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9a51aa0ce64'
down_revision = '11aca2b0af98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
